### ISSUE TITLE
v0.1.0

### ISSUE THREAD

**Issue by furpu** [furpu/ziwt#2]
# Release Plan - v0.1.0

Version 0.1.0 will be released once we have the minimum requirements for a JWT library implementation according to [RFC 7519](https://datatracker.ietf.org/doc/html/rfc7519#section-8).

## Tasks

- [x] HS256 sign and verify
- [x] Unsecured JWTs (i.e. alg = "none")
- [x] JWT encode
- [x] JWT decode
- [x] Tie alg + key in a struct in `Codec`
- #1
